create table authority (
   id int8 not null,
   value varchar(20) not null,
   primary key (id)
);

create table checkout (
   id int8 not null,
   created_at timestamp not null,
   updated_at timestamp,
   address_city varchar(100),
   address_cityarea varchar(100),
   address_country varchar(2),
   address_countryarea varchar(150),
   address_firstname varchar(80),
   address_lastname varchar(80),
   address_phone1 varchar(30),
   address_phone2 varchar(30),
   address_postalcode varchar(30),
   address_streetaddress1 varchar(150),
   address_streetaddress2 varchar(150),
   address_created boolean,
   currency varchar(3) not null,
   email varchar(100) not null,
   ip_address varchar(45) not null,
   mass_unit varchar(2),
   payment_id varchar(250),
   payment_token varchar(250),
   price int8 not null,
   savecustomeraddresses boolean,
   savepaymentmethodasdefault boolean,
   shippingaddress_city varchar(100),
   shippingaddress_cityarea varchar(100),
   shippingaddress_country varchar(2),
   shippingaddress_countryarea varchar(150),
   shippingaddress_firstname varchar(80),
   shippingaddress_lastname varchar(80),
   shippingaddress_phone1 varchar(30),
   shippingaddress_phone2 varchar(30),
   shippingaddress_postalcode varchar(30),
   shippingaddress_streetaddress1 varchar(150),
   shippingaddress_streetaddress2 varchar(150),
   shippingaddress_created boolean,
   shippingmethod_name varchar(100),
   shippingmethod_amount int8,
   shippingmethod_type varchar(7),
   shipping_required boolean not null,
   total_mass int4,
   usessingleaddress boolean,
   primary key (id)
);

create table checkoutline (
   id int8 generated by default as identity,
   product_name varchar(100) not null,
   quantity int4 not null,
   shipping_required boolean not null,
   unit_price_amount int8 not null,
   variant_name varchar(100),
   checkout_id int8 not null,
   product_id int8,
   primary key (id)
);

create table configuration (
   id int8 not null,
   currency varchar(3) not null,
   mass_unit varchar(2) not null,
   profile varchar(10) not null,
   primary key (id)
);

create table "order" (
   id int8 generated by default as identity,
   created_at timestamp not null,
   updated_at timestamp,
   address_city varchar(100),
   address_cityarea varchar(100),
   address_country varchar(2),
   address_countryarea varchar(150),
   address_firstname varchar(80),
   address_lastname varchar(80),
   address_phone1 varchar(30),
   address_phone2 varchar(30),
   address_postalcode varchar(30),
   address_streetaddress1 varchar(150),
   address_streetaddress2 varchar(150),
   captured_amount int8 not null,
   currency varchar(3) not null,
   email varchar(100) not null,
   ip_address varchar(45) not null,
   payment_id varchar(250) not null,
   previous_status varchar(20),
   shippingaddress_city varchar(100),
   shippingaddress_cityarea varchar(100),
   shippingaddress_country varchar(2),
   shippingaddress_countryarea varchar(150),
   shippingaddress_firstname varchar(80),
   shippingaddress_lastname varchar(80),
   shippingaddress_phone1 varchar(30),
   shippingaddress_phone2 varchar(30),
   shippingaddress_postalcode varchar(30),
   shippingaddress_streetaddress1 varchar(150),
   shippingaddress_streetaddress2 varchar(150),
   shippingmethod_name varchar(100),
   shippingmethod_amount int8,
   shippingmethod_type varchar(7),
   status varchar(20) not null,
   customer_id int8,
   primary key (id)
);

create table orderfulfillment (
   id int8 generated by default as identity,
   completed boolean not null,
   tracking_number varchar(50),
   order_id int8 not null,
   primary key (id)
);

create table orderfulfillmentline (
   id int8 generated by default as identity,
   quantity int4 not null,
   orderfulfillment_id int8 not null,
   orderline_id int8 not null,
   primary key (id)
);

create table orderline (
   id int8 generated by default as identity,
   fulfilled_quantity int4 not null,
   product_name varchar(100) not null,
   quantity int4 not null,
   reserved_quantity int4 not null,
   shipping_required boolean not null,
   unit_price_amount int8 not null,
   variant_name varchar(100),
   order_id int8 not null,
   product_id int8,
   primary key (id)
);

create table product (
   id int8 generated by default as identity,
   default_price int8 not null,
   description varchar(250),
   digital boolean not null,
   image_filename varchar(100),
   last_published timestamp,
   last_unpublished timestamp,
   name varchar(100) not null,
   published boolean not null,
   category_id int8,
   default_variant_id int8,
   primary key (id)
);

create table product_producttag (
   product_id int8 not null,
   producttag_id int8 not null,
   primary key (product_id, producttag_id)
);

create table productcategory (
   id int8 generated by default as identity,
   description varchar(250),
   image_filename varchar(100),
   lft int4 not null,
   name varchar(100) not null,
   rgt int4 not null,
   parent_id int8,
   root_id int8,
   primary key (id)
);

create table producttag (
   id int8 generated by default as identity,
   name varchar(100) not null,
   primary key (id)
);

create table productvariant (
   id int8 generated by default as identity,
   mass int4,
   name varchar(100),
   price int8,
   product_id int8 not null,
   primary key (id)
);

create table productvariantimage (
   id int8 generated by default as identity,
   filename varchar(100) not null,
   variant_id int8 not null,
   primary key (id)
);

create table role (
   id int8 not null,
   type varchar(20) not null,
   primary key (id)
);

create table role_authority (
   role_id int8 not null,
   authority_id int8 not null,
   primary key (role_id, authority_id)
);

create table shippingcountry (
   id int8 not null,
   code varchar(2) not null,
   zone_id int8,
   primary key (id)
);

create table shippingmethod (
   id int8 generated by default as identity,
   max_value int8 not null,
   min_value int8 not null,
   name varchar(100) not null,
   rate int8 not null,
   type varchar(7) not null,
   zone_id int8 not null,
   primary key (id)
);

create table shippingzone (
   id int8 generated by default as identity,
   name varchar(100) not null,
   primary key (id)
);

create table uploadedimage (
   id uuid not null,
   created_at timestamp not null,
   filename varchar(100) not null,
   primary key (id)
);

create table "user" (
   id int8 generated by default as identity,
   created_at timestamp not null,
   default_payment_method_id varchar(150),
   email varchar(100),
   enabled boolean not null,
   external_id varchar(150),
   password varchar(150),
   verified boolean not null,
   verified_at timestamp,
   role_id int8 not null,
   primary key (id)
);

create table useraddress (
   id int8 generated by default as identity,
   address_city varchar(100),
   address_cityarea varchar(100),
   address_country varchar(2),
   address_countryarea varchar(150),
   address_firstname varchar(80),
   address_lastname varchar(80),
   address_phone1 varchar(30),
   address_phone2 varchar(30),
   address_postalcode varchar(30),
   address_streetaddress1 varchar(150),
   address_streetaddress2 varchar(150),
   user_id int8 not null,
   primary key (id)
);

create table userverificationtoken (
   id uuid not null,
   created_at timestamp not null,
   user_id int8 not null,
   primary key (id)
);

alter table if exists authority
   add constraint UK_2pa69ddvnicncbohqep2gbwkt unique (value);
create index IDXgrcoekcm0700pv7ck9hvwak0r on checkoutline (checkout_id);
create index IDXkuc83exp7pxv5wp69uwxtkvao on checkoutline (product_id);

alter table if exists configuration
   add constraint UK_kc261y0pv2vb7d442n8cd3i6d unique (profile);
create index IDXsgoccfhg0ykc0l5fntawsxm1v on "order" (customer_id);
create index IDXha2ue6kvsq3jcqxeurwflh5dw on orderfulfillment (order_id);
create index IDX7irjutjyti0oprmhochedg017 on orderfulfillmentline (orderline_id);
create index IDXtoqpfrogeeeubfbpwjj4ue0ww on orderfulfillmentline (orderfulfillment_id);
create index IDXb2n09agb2c35jowwea2wnickh on orderline (order_id);
create index IDXiuxyxexifqaer7699nid52rry on orderline (product_id);
create index IDXi6hqikssg27aganjlm1dyee5s on productvariant (product_id);
create index IDX370c4glhyf9b5olxyew6uvgo on productvariantimage (variant_id);

alter table if exists role
   add constraint UK_93vn3jeavtylq20tjdx2p2kkd unique (type);
create index IDXrnf5gg8nfpuulpes3mbt5c5y4 on shippingcountry (zone_id);

alter table if exists shippingcountry
   add constraint UK_arkfddwv4ujx67owld05ob40b unique (code);

alter table if exists uploadedimage
   add constraint UK_59b0k8al7f94xv2bbkkh3nojy unique (filename);
create index IDXs6aalnvk8m3fdmp9791g6cbbm on "user" (role_id);

alter table if exists "user"
   add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);
create index IDXlm3lm212adwiaxok0htlu6wdd on useraddress (user_id);

alter table if exists userverificationtoken
   add constraint UK_ksla44dkgffml2ntgik4dhffd unique (user_id);

alter table if exists checkout
   add constraint FKants0r8atoy4fyt6qls2yvylj
   foreign key (id)
   references "user";

alter table if exists checkoutline
   add constraint FKjarxgoovwm3qyuydq9l2isty5
   foreign key (checkout_id)
   references checkout;

alter table if exists checkoutline
   add constraint FKt7ll15sug8wyum11f8llbmi6d
   foreign key (product_id)
   references product;

alter table if exists "order"
   add constraint FK72gc4p3rrmaenbost5ksr5m9p
   foreign key (customer_id)
   references "user";

alter table if exists orderfulfillment
   add constraint FK17qfdpx5yu1r516nl3g0fokm3
   foreign key (order_id)
   references "order";

alter table if exists orderfulfillmentline
   add constraint FKdgaxpoj424909voubrl01a5p4
   foreign key (orderfulfillment_id)
   references orderfulfillment;

alter table if exists orderfulfillmentline
   add constraint FKqq21e3pl7xppmvwotsdsum1u2
   foreign key (orderline_id)
   references orderline;

alter table if exists orderline
   add constraint FK36omvt1tn62h973qpdm1ipr3h
   foreign key (order_id)
   references "order";

alter table if exists orderline
   add constraint FKr1od9vmk4y5fqamfadvclmcpu
   foreign key (product_id)
   references product;

alter table if exists product
   add constraint FK4d8llfhcjqt2uems0ev0s2lkl
   foreign key (category_id)
   references productcategory;

alter table if exists product
   add constraint FKfnibmygthy5fnkhouu7wochar
   foreign key (default_variant_id)
   references productvariant;

alter table if exists product_producttag
   add constraint FK1ms104tnndrgsm0gcj22rw3aq
   foreign key (product_id)
   references product;

alter table if exists product_producttag
   add constraint FKlpwq0efqecveg6x9ms3bsihs4
   foreign key (producttag_id)
   references producttag;

alter table if exists productcategory
   add constraint FKpjkeimc8ug75h953j9t4piblm
   foreign key (parent_id)
   references productcategory;

alter table if exists productcategory
   add constraint FKcw5q0lybfh7785jy9sy7bedpq
   foreign key (root_id)
   references productcategory;

alter table if exists productvariant
   add constraint FKcqmeqsqwhxhx6cipyg71m9rgi
   foreign key (product_id)
   references product;

alter table if exists productvariantimage
   add constraint FK2n052sikmxra9lfj65lw52fgb
   foreign key (variant_id)
   references productvariant;

alter table if exists role_authority
   add constraint FKqbri833f7xop13bvdje3xxtnw
   foreign key (authority_id)
   references authority;

alter table if exists role_authority
   add constraint FK2052966dco7y9f97s1a824bj1
   foreign key (role_id)
   references role;

alter table if exists shippingcountry
   add constraint FKhull0elpxh4dkii1nl3vv9hhn
   foreign key (zone_id)
   references shippingzone;

alter table if exists shippingmethod
   add constraint FK5o56gqpf0waahh4lm5d3k8ylm
   foreign key (zone_id)
   references shippingzone;

alter table if exists "user"
   add constraint FKdl9dqp078pc03g6kdnxmnlqpc
   foreign key (role_id)
   references role;

alter table if exists useraddress
   add constraint FKimr2a73pv35t7t1cjjpldjsqq
   foreign key (user_id)
   references "user";

alter table if exists userverificationtoken
   add constraint FK3mydh2l3f43kt2bfj63w08875
   foreign key (user_id)
   references "user";
